Promises, Async and Await
-------------------------


Promises
--------

### creating a promise

```javascript
const myFirstPromise = new Promise((resolve, reject) => {
  // do something asynchronous which eventually calls either:
  //
  //   resolve(someValue); // fulfilled
  // or
  //   reject("failure reason"); // rejected
});
```


---


// ex
```javascript
let promiseToCleanTheRoom = new Promise(function(resolve, reject){

  //cleaning the room
  let isClean = true;

  if(isClean) {
    resolve('clean')
  } else {
    reject('not clean')
  }

})
```

// the promise is defined above

// below we call the promise function, notice the callback within .then will catch what is passed into the resolve function

```javascript

promiseToCleanTheRoom
  .then(function (fromResolve) {

  console.log('the room is' + fromResolve)

})
  .catch(function (fromReject) {

  console.log('the room is ' + fromReject)

})
```



---



### .catch

```javascript
new Promise((resolve, reject) => {
    console.log('Initial');

    resolve();
})
.then(() => {
    throw new Error('Something failed');

    console.log('Do this');
})
.catch(() => {
    console.log('Do that');
})
.then(() => {
    console.log('Do this whatever happened before');
});
```

// Note that the text Do this is not outputted because the Something failed error caused a rejection

// output
```
Initial
Do that
Do this whatever happened before
```


------



### promise.resolve() / promise.reject()

// Promise.resolve() and Promise.reject() are shortcuts to manually create an already resolved or rejected promise respectively


------


### promise.all() / promise.wait()

// Promise.all() and Promise.race() are two composition tools for running asynchronous operations in parallel.









----------------------------------------------------------------








Async
-----


// ex,
```javascript
function resolveAfter2Seconds(x) {
  return new Promise(resolve => {
    setTimeout(() => {
      resolve(x);
    }, 2000);
  });
}


async function add1(x) {
  const a = await resolveAfter2Seconds(20);
  const b = await resolveAfter2Seconds(30);
  return x + a + b;
}

add1(10).then(v => {
  console.log(v);  // prints 60 after 4 seconds.
});
```



---



// ex, with try catch
```javascript
async function getProcessedData(url) {
  let v;
  try {
    v = await downloadData(url);
  } catch(e) {
    v = await downloadFallbackData(url);
  }
  return processDataInWorker(v);
}
```






------







### example

```javascript
const deansProm = (input) => {
    return new Promise ((resolve, reject) => {
        setTimeout(() => {
            if (!input) {
                reject('Your input was falsey giiirlll \n')
            } else {
                resolve('Your input was ' + input + '\n')
            }
        })
    })
}

// this will fail
deansProm()
    .then((resolveValue) => {
        console.log(resolveValue)
    })
    .then((thenInput) => {
        console.log('will I see this?')
    })
    .catch((error) => {
        console.log('No success', error)
    })

deansProm('wubalubadubdub')
    .then((resolveValue) => {
        console.log('Success!! ', resolveValue)
    })
    .catch((error) => {
        console.log('No success', error)
    })


async function deansAsync(input) {
    let output
    try {
        output = 'cool yoy did is with async!! ' + await deansProm(input)
    } catch(err) {
        output = 'you got a problem ' + err
    }
    console.log(output)
}

deansAsync('please work')




```




















